#!/usr/bin/env bash

#
# this script try to test every python files in the current directory and
# in its subdirectories.  it used pytest and python2
#

export PYTHON_EXECUTABLE="python2"

check_test
