#!/usr/bin/env bash

#
# this script try to test every python files in the current directory and
# in its subdirectories.  it used pytest and python3
#

export PYTHON_EXECUTABLE="python3"

check_test
