#!/usr/bin/env bash

#
# this script try to test a python file.  it used pytest and python3
#

source test_function

if [[ $# -lt 1 ]]; then
    echo "expect a file path as argument"
    exit
fi

if [[ !( -f $1 ) ]]; then
    echo "file '$1' does not exist"
    exit
fi

build_module_name $1
module_name=$RESULT

build_test_file_path $1
test_file_path=$RESULT

if [[ !( -f $test_file_path ) ]]; then
    echo "test file does not exist"
    exit
fi

python3 -m pytest --cov=$module_name --cov-report=term-missing $test_file_path
