#!/usr/bin/env bash

git_status=$(git status)

if [[ "$git_status" == *"not a git repository"* ]]; then
    echo "not a git repository"
    exit 1
fi

current_branch=`git rev-parse --abbrev-ref HEAD`

for branch in `git branch -l | tr '*' ' '`;
do
    #ignore master
    if [ $branch == "master" ]
    then
        continue
    fi
    
    #ignore dev
    if [ $branch == "dev" ]
    then
        continue
    fi

    git co $branch
    
    #stop if any error
    git rebase origin/dev || exit
done

git co $current_branch
