#!/usr/bin/env bash

function stop_if_failure {
    # if the last return code is different from zero, stop the script
    if [ $? -ne 0 ]; then
        quit "$1"
    fi
}

function remove_directory {
    if [[ -e $1 ]]; then
        if [[ !( -d $1 ) ]]; then
            quit "failed to remove directory '$1', not a directory"
        fi

        rm -r $1
        stop_if_failure "failed to remove directory $1"
    fi
}

function directory_exists {
    if [[ !( -d "$1" ) ]]; then
        if [[ -e "$1" ]]; then
            quit "$1 file is not a directory"
        fi

        quit "no $1 directory found"
    fi
}

function file_exists {
    if [[ !( -f "$1" ) ]]; then
        quit "no $1 found in the current directory."
    fi
}

function containsElement {
  local e
  for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
  return 1
}

function msg {
    echo
    echo -e "!!!!  $1  !!!!"
    echo
}

function quit {
    # print message then quit
    msg "$1"
    exit
}
